module.exports = {
  plugins: ['@stylistic'],
  rules: {
    // "@stylistic/eslint-plugin": "1.5.1",

    '@stylistic/array-bracket-newline': ['warn', 'consistent'],
    '@stylistic/array-bracket-spacing': ['warn', 'never'],
    '@stylistic/array-element-newline': ['off'],
    '@stylistic/arrow-parens': ['warn', 'always'],
    '@stylistic/arrow-spacing': ['warn', { before: true, after: true }],
    '@stylistic/block-spacing': ['warn', 'always'],
    '@stylistic/brace-style': ['warn', '1tbs', { allowSingleLine: true }],
    '@stylistic/comma-dangle': ['warn', 'always-multiline'],
    '@stylistic/comma-spacing': ['warn', { before: false, after: true }],
    '@stylistic/comma-style': ['warn', 'last'],
    '@stylistic/computed-property-spacing': ['warn', 'never'],
    '@stylistic/dot-location': ['warn', 'property'],
    '@stylistic/eol-last': ['warn', 'always'],
    '@stylistic/func-call-spacing': ['warn', 'never'],
    '@stylistic/function-call-argument-newline': ['warn', 'consistent'],
    '@stylistic/function-call-spacing': ['warn', 'never'],
    '@stylistic/function-paren-newline': ['warn', 'multiline-arguments'],
    '@stylistic/generator-star-spacing': ['warn', { before: true, after: true }],
    '@stylistic/implicit-arrow-linebreak': ['warn', 'beside'],
    '@stylistic/indent': ['warn', 2, { SwitchCase: 1, offsetTernaryExpressions: true }],
    '@stylistic/indent-binary-ops': ['warn', 2],
    '@stylistic/key-spacing': ['warn', { beforeColon: false, afterColon: true, mode: 'strict' }],
    '@stylistic/keyword-spacing': ['warn', { before: true, after: true }],
    '@stylistic/linebreak-style': ['warn', 'unix'],
    '@stylistic/lines-around-comment': ['off'],
    '@stylistic/lines-between-class-members': ['warn', 'always'],
    '@stylistic/max-len': ['off'],
    '@stylistic/max-statements-per-line': ['warn', { max: 3 }],
    '@stylistic/multiline-ternary': ['off'],
    '@stylistic/new-parens': ['warn', 'always'],
    '@stylistic/newline-per-chained-call': ['off'],
    '@stylistic/no-confusing-arrow': ['error', { allowParens: true }],
    '@stylistic/no-extra-parens': ['off'],
    '@stylistic/no-extra-semi': ['warn'],
    '@stylistic/no-floating-decimal': ['warn'],
    '@stylistic/no-mixed-operators': ['warn'],
    '@stylistic/no-mixed-spaces-and-tabs': ['warn'],
    '@stylistic/no-multi-spaces': ['warn'],
    '@stylistic/no-multiple-empty-lines': ['warn', { max: 3, maxEOF: 1, maxBOF: 1 }],
    '@stylistic/no-tabs': ['warn'],
    '@stylistic/no-trailing-spaces': ['warn'],
    '@stylistic/no-whitespace-before-property': ['warn'],
    '@stylistic/nonblock-statement-body-position': ['warn'],
    '@stylistic/object-curly-newline': ['warn', { consistent: true }],
    '@stylistic/object-curly-spacing': ['warn', 'always'],
    '@stylistic/object-property-newline': ['off'],
    '@stylistic/one-var-declaration-per-line': ['off'],
    '@stylistic/operator-linebreak': ['warn', 'after', { overrides: { '?': 'before', ':': 'before' } }],
    '@stylistic/padded-blocks': ['off'],
    '@stylistic/padding-line-between-statements': ['off'],
    '@stylistic/quote-props': ['error', 'as-needed', { numbers: true }],
    '@stylistic/quotes': ['warn', 'single'],
    '@stylistic/rest-spread-spacing': ['warn', 'never'],
    '@stylistic/semi': ['warn', 'never'],
    '@stylistic/semi-spacing': ['warn', { before: false, after: true }],
    '@stylistic/semi-style': ['warn', 'last'],
    '@stylistic/space-before-blocks': ['warn'],
    '@stylistic/space-before-function-paren': ['warn', { anonymous: 'always', named: 'never', asyncArrow: 'always' }],
    '@stylistic/space-in-parens': ['warn', 'never'],
    '@stylistic/space-infix-ops': ['warn'],
    '@stylistic/space-unary-ops': ['warn', { words: true, nonwords: false }],
    '@stylistic/spaced-comment': [
      'error',
      'always',
      {
        line: {
          markers: ['/'],
          exceptions: ['-', '+'],
        },
        block: {
          markers: ['!'],
          exceptions: ['*'],
          balanced: true,
        },
      },
    ],
    '@stylistic/switch-colon-spacing': ['warn', { before: false, after: true }],
    '@stylistic/template-curly-spacing': ['warn', 'never'],
    '@stylistic/template-tag-spacing': ['warn', 'never'],
    '@stylistic/wrap-iife': ['warn', 'inside', { functionPrototypeMethods: true }],
    '@stylistic/wrap-regex': ['off'],
    '@stylistic/yield-star-spacing': ['warn', { before: true, after: true }],

    /* jsx */
    '@stylistic/jsx-child-element-spacing': ['off'],
    '@stylistic/jsx-closing-bracket-location': ['off'],
    '@stylistic/jsx-closing-tag-location': ['off'],
    '@stylistic/jsx-curly-brace-presence': ['off'],
    '@stylistic/jsx-curly-newline': ['off'],
    '@stylistic/jsx-curly-spacing': ['off'],
    '@stylistic/jsx-equals-spacing': ['off'],
    '@stylistic/jsx-first-prop-new-line': ['off'],
    '@stylistic/jsx-indent': ['off'],
    '@stylistic/jsx-indent-props': ['off'],
    '@stylistic/jsx-max-props-per-line': ['off'],
    '@stylistic/jsx-newline': ['off'],
    '@stylistic/jsx-one-expression-per-line': ['off'],
    '@stylistic/jsx-props-no-multi-spaces': ['off'],
    '@stylistic/jsx-quotes': ['warn', 'prefer-double'],
    '@stylistic/jsx-self-closing-comp': ['off'],
    '@stylistic/jsx-sort-props': ['off'],
    '@stylistic/jsx-tag-spacing': ['off'],
    '@stylistic/jsx-wrap-multilines': ['off'],

    /* typescript */
    '@stylistic/member-delimiter-style': [
      'error',
      {
        multiline: {
          delimiter: 'none',
          requireLast: true,
        },
        singleline: {
          delimiter: 'semi',
          requireLast: false,
        },
        multilineDetection: 'brackets',
      },
    ],
    '@stylistic/type-annotation-spacing': ['warn'],
    '@stylistic/type-generic-spacing': ['warn'],
    '@stylistic/type-named-tuple-spacing': ['warn'],
  },
}
