
const stylisticRules = {
  // "@stylistic/eslint-plugin": "2.1.0",

  'style/array-bracket-newline': ['warn', 'consistent'],
  'style/array-bracket-spacing': ['warn', 'never'],
  'style/array-element-newline': ['off'],
  'style/arrow-parens': ['warn', 'always'],
  'style/arrow-spacing': ['warn', { before: true, after: true }],
  'style/block-spacing': ['warn', 'always'],
  'style/brace-style': ['warn', '1tbs', { allowSingleLine: true }],
  'style/comma-dangle': ['warn', 'always-multiline'],
  'style/comma-spacing': ['warn', { before: false, after: true }],
  'style/comma-style': ['warn', 'last'],
  'style/computed-property-spacing': ['warn', 'never'],
  'style/dot-location': ['warn', 'property'],
  'style/eol-last': ['warn', 'always'],
  'style/func-call-spacing': ['warn', 'never'],
  'style/function-call-argument-newline': ['warn', 'consistent'],
  'style/function-call-spacing': ['warn', 'never'],
  'style/function-paren-newline': ['warn', 'multiline-arguments'],
  'style/generator-star-spacing': ['warn', { before: true, after: true }],
  'style/implicit-arrow-linebreak': ['warn', 'beside'],
  'style/indent': ['warn', 2, { SwitchCase: 1, offsetTernaryExpressions: true }],
  'style/indent-binary-ops': ['warn', 2],
  'style/key-spacing': ['warn', { beforeColon: false, afterColon: true, mode: 'strict' }],
  'style/keyword-spacing': ['warn', { before: true, after: true }],
  'style/line-comment-position': ['off'],
  'style/linebreak-style': ['warn', 'unix'],
  'style/lines-around-comment': ['off'],
  'style/lines-between-class-members': ['off'],
  'style/max-len': ['off'],
  'style/max-statements-per-line': ['warn', { max: 3 }],
  'style/member-delimiter-style': [
    'warn',
    {
      multiline: {
        delimiter: 'none',
        requireLast: true,
      },
      singleline: {
        delimiter: 'semi',
        requireLast: false,
      },
      multilineDetection: 'brackets',
    },
  ],
  'style/multiline-comment-style': ['off'],
  'style/multiline-ternary': ['off'],
  'style/new-parens': ['warn', 'always'],
  'style/newline-per-chained-call': ['off'],
  'style/no-confusing-arrow': ['warn', { allowParens: true }],
  'style/no-extra-parens': ['off'],
  'style/no-extra-semi': ['warn'],
  'style/no-floating-decimal': ['warn'],
  'style/no-mixed-operators': ['warn'],
  'style/no-mixed-spaces-and-tabs': ['warn'],
  'style/no-multi-spaces': ['warn'],
  'style/no-multiple-empty-lines': ['warn', { max: 3, maxEOF: 1, maxBOF: 1 }],
  'style/no-tabs': ['warn'],
  'style/no-trailing-spaces': ['warn'],
  'style/no-whitespace-before-property': ['warn'],
  'style/nonblock-statement-body-position': ['warn'],
  'style/object-curly-newline': ['warn', { consistent: true }],
  'style/object-curly-spacing': ['warn', 'always'],
  'style/object-property-newline': ['off'],
  'style/one-var-declaration-per-line': ['off'],
  'style/operator-linebreak': ['warn', 'after', { overrides: { '?': 'before', ':': 'before' } }],
  'style/padded-blocks': ['off'],
  'style/padding-line-between-statements': ['off'],
  'style/quote-props': ['warn', 'as-needed', { numbers: false }],
  'style/quotes': ['warn', 'single'],
  'style/rest-spread-spacing': ['warn', 'never'],
  'style/semi': ['warn', 'never'],
  'style/semi-spacing': ['warn', { before: false, after: true }],
  'style/semi-style': ['warn', 'last'],
  'style/space-before-blocks': ['warn'],
  'style/space-before-function-paren': ['warn', { anonymous: 'always', named: 'never', asyncArrow: 'always' }],
  'style/space-in-parens': ['warn', 'never'],
  'style/space-infix-ops': ['warn'],
  'style/space-unary-ops': ['warn', { words: true, nonwords: false }],
  'style/spaced-comment': [
    'warn',
    'always',
    {
      line: {
        markers: ['/'],
        exceptions: ['-', '+'],
      },
      block: {
        markers: ['!'],
        exceptions: ['*'],
        balanced: true,
      },
    },
  ],
  'style/switch-colon-spacing': ['warn', { before: false, after: true }],
  'style/template-curly-spacing': ['warn', 'never'],
  'style/template-tag-spacing': ['warn', 'never'],
  'style/type-annotation-spacing': ['warn'],
  'style/type-generic-spacing': ['warn'],
  'style/type-named-tuple-spacing': ['warn'],
  'style/wrap-iife': ['warn', 'inside', { functionPrototypeMethods: true }],
  'style/wrap-regex': ['off'],
  'style/yield-star-spacing': ['warn', { before: true, after: true }],

  /* jsx */
  'style/jsx-child-element-spacing': ['off'],
  'style/jsx-closing-bracket-location': ['off'],
  'style/jsx-closing-tag-location': ['off'],
  'style/jsx-curly-brace-presence': ['off'],
  'style/jsx-curly-newline': ['off'],
  'style/jsx-curly-spacing': ['off'],
  'style/jsx-equals-spacing': ['off'],
  'style/jsx-first-prop-new-line': ['off'],
  'style/jsx-indent': ['off'],
  'style/jsx-indent-props': ['off'],
  'style/jsx-max-props-per-line': ['off'],
  'style/jsx-newline': ['off'],
  'style/jsx-one-expression-per-line': ['off'],
  'style/jsx-props-no-multi-spaces': ['off'],
  'style/jsx-quotes': ['warn', 'prefer-double'],
  'style/jsx-self-closing-comp': ['off'],
  'style/jsx-sort-props': ['off'],
  'style/jsx-tag-spacing': ['off'],
  'style/jsx-wrap-multilines': ['off'],
}

export default stylisticRules
